### ISSUE TITLE
OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\User_Name\AppData\Roaming\Python\Python311\site-packages\torch\lib\shm.dll" or one of its dependencies.

### ISSUE THREAD

**Issue by MahitejVardhan** [P1855/Object-Detection-on-custom-data-set-using-YOLOv8#1]

**Comment by P1855** [comment]
Can you provide more details of the error

**Comment by MahitejVardhan** [comment]
when i run this
from ultralytics import YOLO

I'm getting this

File ~\AppData\Roaming\Python\Python311\site-packages\ultralytics\__init__.py:5
      1 # Ultralytics YOLO 🚀, AGPL-3.0 license
      3 __version__ = "8.2.17"
----> 5 from ultralytics.data.explorer.explorer import Explorer
      6 from ultralytics.models import RTDETR, SAM, YOLO, YOLOWorld
      7 from ultralytics.models.fastsam import FastSAM

File ~\AppData\Roaming\Python\Python311\site-packages\ultralytics\data\__init__.py:3
      1 # Ultralytics YOLO 🚀, AGPL-3.0 license
----> 3 from .base import BaseDataset
      4 from .build import build_dataloader, build_grounding, build_yolo_dataset, load_inference_source
      5 from .dataset import (
      6     ClassificationDataset,
      7     GroundingDataset,
   (...)
     11     YOLOMultiModalDataset,
     12 )

File ~\AppData\Roaming\Python\Python311\site-packages\ultralytics\data\base.py:15
     13 import numpy as np
     14 import psutil
---> 15 from torch.utils.data import Dataset
     17 from ultralytics.data.utils import FORMATS_HELP_MSG, HELP_URL, IMG_FORMATS
     18 from ultralytics.utils import DEFAULT_CFG, LOCAL_RANK, LOGGER, NUM_THREADS, TQDM

File ~\AppData\Roaming\Python\Python311\site-packages\torch\__init__.py:141
    139                 err = ctypes.WinError(ctypes.get_last_error())
    140                 err.strerror += f' Error loading "{dll}" or one of its dependencies.'
--> 141                 raise err
    143     kernel32.SetErrorMode(prev_error_mode)
    146 def _preload_cuda_deps(lib_folder, lib_name):

OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\User_Name\AppData\Roaming\Python\Python311\site-packages\torch\lib\shm.dll" or one of its dependencies.

**Comment by P1855** [comment]
Did you first run pip install ultralytics in the console before writing the code ?

**Comment by MahitejVardhan** [comment]
no i have directly runned it in the jupyter notebook

**Comment by P1855** [comment]
Try using pycharm community rather than jupyter notebook and try to install ultralytics in the console before running the codes

**Comment by MahitejVardhan** [comment]
can you give me the steps for this pycharm how to run 
actually my project is based on tree sensing 
i have few ipybn files to run and integrate the saved model to html page
so help me out in giving me the steps
and which console is better to use?

**Comment by P1855** [comment]
Actually the reference video of this project is this one ; https://youtu.be/m9fH9OWn8YM?si=Et5zCiTImY1GMU3N
You can refer to this
